name: CI

on:
  push:
    branches: [ test ]
  pull_request:
    branches: [ test ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2 

      - name: Run a one-line script
        run: echo Hello, world!

      - name: run ping script 
        run: ./ping_google_dns.sh
