name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
      - uses: actions/checkout@v2
        with:
                persist-credentials: false

      - name: Run a one-line script
        run: echo Hello, world!

      - name: run ping script 
        run: ./ping_google_dns.sh
