name: CI

on:
  push:
    branches: [ push ]
  pull_request:
    branches: [ push ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2 

      - name: Run a one-line script
        run: echo Hello, world!


      - name: Start container and verify it is working
        run: # set -x
            docker-compose up -d
            docker run --network container:contacts \
              appropriate/curl --retry 10 --retry-delay 1 --retry-connrefused http://localhost:8080/contacts/test
